{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "Emotional Reactions in Literature",

    "output_dir": "../output/",

    # NOTE: This is probably going to be a directory / DB at some point...
    "user_state_dir": "annotation_output",

    "annotation_codebook_url": "https://docs.google.com/document/d/1eXgaOZJDahhZLqYWbLTD_84-d1rnQ4M-bccer3HY6WI",

    "data_files": [
       "data/annotate-erl.json"
    ],

    "item_properties": {
        "id_key": "id",
        #"text_key": "text",
        
        # Sky: Custom ones
        
        "q_quote": "q_quote",
        "q_beginOffset": "q_beginOffset",
        "q_endOffset": "q_endOffset",
        "p_quoted_aliases": "p_quoted_aliases",
        "p_context_aliases": "p_context_aliases",
        
        "paragraph0": "paragraph0",
        "paragraph0_beginOffset": "paragraph0_beginOffset",
        "paragraph0_qc_offsets": "paragraph0_qc_offsets",
        "paragraph0_cc_offsets": "paragraph0_cc_offsets",

        "paragraph1": "paragraph1",
        "paragraph1_beginOffset": "paragraph1_beginOffset",
        "paragraph1_qc_offsets": "paragraph1_qc_offsets",
        "paragraph1_cc_offsets": "paragraph1_cc_offsets",

        "paragraph2": "paragraph2",
        "paragraph2_beginOffset": "paragraph2_beginOffset",
        "paragraph2_qc_offsets": "paragraph2_qc_offsets",
        "paragraph2_cc_offsets": "paragraph2_cc_offsets"
    },
    
    "users": [
        {"user_id": "0", "firstname": "David", "lastname": "Jurgens"},
        {"user_id": "1", "firstname": "Jiaxin", "lastname": "Pei"},
        {"user_id": "2", "firstname": "Naitian", "lastname": "Zhou"},
    ],

    "annotation_files": [
        "../data/examples"
    ],

    "keyword_highlights_file": "config/frame_keywords.tsv",

    "annotation_schemes": [
        {
            "annotation_type": "multiselect",
            "name": "Emotional Change",
            "labels": [
                { "name": "Anger",
                  "tooltip_file": "config/tooltips/ig_economic.html"
                },
                {
                  "name": "Fear",
                  "tooltip_file": "config/tooltips/ig_capacity.html"
                },
                { "name": "Sadness",
                  "tooltip_file": "config/tooltips/ig_morality.html"
                },
                { "name": "Disgust",
                  "tooltip_file": "config/tooltips/ig_fairness.html",
                },
                { "name": "Surprise",
                  "tooltip_file": "config/tooltips/ig_legality.html",
                },
                { "name": "Anticipation",
                  "tooltip_file": "config/tooltips/ig_crime.html",
                },
                { "name": "Trust",
                  "tooltip_file": "config/tooltips/ig_security.html",
                },
                { "name": "Joy",
                  "tooltip_file": "config/tooltips/ig_health.html",
                },
                "None"
            ]
        },

        {
            "annotation_type": "slider",
            "name": "Intensity of Change",
            "labels": [
                { "name": "No Affect",
                  "tooltip_file": "config/tooltips/sp_global.html"
                },
                { "name": "Minor Affect",
                  "tooltip_file": "config/tooltips/sp_humanitarian.html"
                },
                { "name": "Neutral",
                  "tooltip_file": "config/tooltips/sp_war.html"
                },
                { "name": "Moderate Affect",
                  "tooltip_file": "config/tooltips/sp_discrimination.html"
                },
                { "name": "Major Affect",
                  "tooltip_file": "config/tooltips/sp_diversity.html"
                }
            ]
            
        }
    ],


    # Visualization
    "html_template": "templates/multiple_choice.html",
    "header_file": "templates/header.html",

    # This is where the actual HTML files will be generated
    "site_dir": "potato/templates/",

    # comment    
    "state_update_rate": 1,


}
        
